apiVersion: ingress.kb.dev/v1beta1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  image: nginx:1.27
  replicas: 2
  enable_ingress: true
  enable_service: true
